[package]
name = "variables"
version = "2.3.4"
authors = ["Z-M-Huang <25124355+Z-M-Huang@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
